input_data:
 	 file1: "../data/raw/raw/Unicorn_Companies.csv"
output_data:
  	file1: "../data/clean/companies_cleaned.parquet"
 	file2: "../data/clean/final_analysis_merged.parquet”
 file3: "../data/clean/unicorns_standardized.parquet”

